### PR TITLE
DBZ-2525 Generifying exclusion of columns from snapshotting

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-2525

### CODE REVIEW

**Comment by ani-sha** [comment]
@gunnarmorling  I am not sure what this test failure is about. Could you please take a look into the test failure in `Db2CaseSensitiveObjectIT#testCaseSensitiveSchemaAndTable`?

**Comment by gunnarmorling** [comment]
@ani-sha, do you also get failure when running the test locally?

**Comment by ani-sha** [comment]
@gunnarmorling yes, the same test failed.

**Comment by gunnarmorling** [comment]
The test failure should be addressed via https://github.com/debezium/debezium/pull/2659. Did you take a look at the output on CI btw., @ani-sha? The failure was pretty evident in the logs there. Let me know if you want to do a quick screen share session so to show where I looked for identifying the issue.

**Comment by ani-sha** [comment]
Yes @gunnarmorling, looking at the logs I could see the failures. But why is it exactly that Db2 wouldn't take `tableName.columnName` format?

**Comment by gunnarmorling** [comment]
> But why is it exactly that Db2 wouldn't take tableName.columnName format?

Good question, and it's not quite clear to me tbh. But given the qualification shouldn't be needed to begin with, I didn't bother thinking much about it :)

**Comment by ani-sha** [comment]
@gunnarmorling CI checks done, good for merge. :heavy_check_mark:

**Comment by gunnarmorling** [comment]
Woohoo, at last :)

**Pull request merged**
