### PR TITLE
DBZ-8380 Migrate DB2 testsuite to async engine

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-8380

### CODE REVIEW

**Comment by vjuranek** [comment]
I think these two (or batter to say `IncrementalSnapshotIT`) fails randomly quite often:
```
Error:  Failures: 
Error:    IncrementalSnapshotIT>AbstractIncrementalSnapshotTest.snapshotWithAdditionalConditionWithSurrogateKey:1036->AbstractConnectorTest.assertNoRecordsToConsume:1026 expected:<[tru]e> but was:<[fals]e>
Error:    IncrementalSnapshotIT>AbstractIncrementalSnapshotTest.snapshotWithNewAdditionalConditionsField:942->AbstractConnectorTest.assertNoRecordsToConsume:1026 expected:<[tru]e> but was:<[fals]e>
[INFO] 
Error:  Tests run: 83, Failures: 2, Errors: 0, Skipped: 3
```

**Comment by jpechane** [comment]
I se them failing locally now too

**Comment by vjuranek** [comment]
ok, I'll take a look (on my machine it's passing, but I haven't run it many times)

**Comment by vjuranek** [comment]
Everything passing now, thus merging.

**Pull request merged**
