### PR TITLE
DBZ-7516 Fix reselect test failure, use enable table CDC callback

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-7516

### CODE REVIEW

**Comment by Naros** [comment]
@jpechane this should finally get Db2 to green across the board.

**Review by mfvitale — APPROVED** [review]

**Comment by jpechane** [comment]
@Naros Great job, applied, thanks!

**Comment by jpechane** [comment]
@Naros I tried to apply the PR to 2.5 but it seems that additional commits are needed maybe including backports in core. Could you please take a look?

**Comment by jpechane** [comment]
Backported

**Pull request merged**
